---
lab_name: perf-iad3-lab01
config_prefix: openstack
enable_interfaces: False

user_config:
  container_cidr: 172.29.236.0/22
  tunnel_cidr:  172.29.240.0/22
  storage_cidr: 172.29.244.0/22
  used_ips:
    - "172.29.236.1,172.29.236.15"
    - "172.29.236.60,172.29.236.110"
    - "172.29.240.60,172.29.240.110"
    - "172.29.244.60,172.29.244.110"
  internal_lb_vip_address: 172.29.236.10
  external_lb_vip_address: 10.17.137.64
  tunnel_bridge: br-vxlan
  container_bridge: br-mgmt
  lb_name: 687432-lbal1.rackspace.com
  networking:
    - name: container
      bridge: br-mgmt
      container_bridge: br-mgmt
      container_interface: eth1
      container_type: veth
      ip_from_q: container
      is_ssh_address: true
      is_container_address: true
      type: raw
      group_binds:
        - all_containers
        - hosts
    - name: provider
      bridge: br-vlan
      container_interface: eth11
      container_type: veth
      type: vlan
      range: 729:729
      net_name: vlan
      group_binds:
        - neutron_linuxbridge_agent
    - name: tenant
      bridge: br-vxlan
      container_interface: eth10
      container_type: veth
      container_mtu: "9000"
      ip_from_q: tunnel
      type: vxlan
      range: 1:1000
      net_name: vxlan
      group_binds:
        - neutron_linuxbridge_agent
    - name: storage
      bridge: br-storage
      container_interface: eth2
      container_type: veth
      ip_from_q: storage
      type: raw
      container_mtu: "9000"
      group_binds:
        - glance_api
        - cinder_api
        - cinder_volume
        - nova_compute
        - swift_proxy

# tempest net config
tempest_public_provider_net:
  tempest_public_subnet_cidr: "10.50.48.0/22"
  tempest_public_subnet_gateway: "10.50.48.1"
  tempest_public_net_provider_type: "vlan"
  tempest_public_net_physical_type: "vlan"
  tempest_public_net_seg_id: 729
  tempest_public_router_external: True

tempest_private_net:
  tempest_private_subnet_cidr: "192.168.1.0/24"
  tempest_private_net_provider_type: "vxlan"
  tempest_private_net_seg_id: 1

vgs:
  - name: cinder-volumes
    device: /dev/sdb

# Add tempate code
keystone:
  service:
    adminuri_insecure: True
    internaluri_insecure: True

# Need to add template code
nova:
  allocation_ratios:
    cpu: 10.0
    ram: 1.5
    max_instance_per_host: 500

cinder_storage:
  backends:
    lvm:
      volume_group: cinder-volumes
      volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
      volume_backend_name: LVM_iSCSI
  # need to add template code
  volume_clear: "none"

swift_config:
  part_power: 14
  weight: 200
  min_part_hours: 1
  repl_number: 3
  region: 1
  storage_network: 'br-storage'
  replication_network: 'br-storage'
  drives:
    - name: sdb
    - name: sdc
    - name: sdd
    - name: sde
    - name: sdf
    - name: sdg
    - name: sdh
    - name: sdi
    - name: sdj
    - name: sdk
  mount_point: /srv/node
  mount_opts: 'noatime,nodiratime,nobarrier,logbufs=8'
  account: "service:glance"
  container: glance
  storage_policies:
    - name: gold
      index: 0
      default: True

ceph_config:
  glance_default_store: rbd
  nova_libvirt_images_rbd_pool: vms
  nova_force_config_drive: False
  nova_libvirtd_listen_tls: 0
  nova_libvirtd_listen_tcp: 1
  nova_libvirtd_auth_tcp: none
  volume_driver: cinder.volume.drivers.rbd.RBDDriver
  rbd_pool: volumes
  rbd_ceph_conf: /etc/ceph/ceph.conf
  rbd_flatten_volume_from_snapshot: 'false'
  rbd_max_clone_depth: 5
  rbd_store_chunk_size: 4
  rados_connect_timeout: -1
  glance_api_version: 2
  volume_backend_name: ceph
  monitor_interface: eth1
  public_network: 172.29.236.0/22
  cluster_network: 192.168.1.0/24
  devices:
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    - /dev/sdf
    - /dev/sdg
  raw_journal_devices:
    - /dev/sdb
    - /dev/sdb
    - /dev/sdb
    - /dev/sdb
    - /dev/sdb

networking:
  - name: lo
    type: loopback
  - name: p1p1
    type: manual
    directives:
      - "bond-master bond0"
      - "bond-primary p1p1"
  - name: p4p1
    type: manual
    directives:
      - "bond-master bond0"
  - name: em1
    type: static
    directives:
    - "netmask {{ ansible_em1.ipv4.netmask }}"
    - "post-up ip route add 10.191.192.0/18 via 10.136.157.225 dev em1"
    - "address {{ ansible_em1.ipv4.address }}"
  - name: p1p2
    type: manual
    directives:
      - "bond-master bond1"
      - "bond-primary p1p2"
  - name: p4p2
    type: manual
    directives:
      - "bond-master bond1"
  - name: bond0
    type: static
    directives:
      - "bond-slaves none"
      - "bond-mode active-backup"
      - "bond-miimon 100"
      - "bond-downdelay 200"
      - "bond-updelay 200"
      - "address {{ ansible_default_ipv4.address }}"
      - "netmask {{ ansible_default_ipv4.netmask }}"
      - "gateway {{ ansible_default_ipv4.gateway }}"
      - "dns-nameservers 69.20.0.164 69.20.0.196"
      - "dns-search qe1.iad3.rackspace.com"
  - name: bond1
    type: manual
    directives:
      - "bond-slaves none"
      - "bond-mode active-backup"
      - "bond-miimon 100"
      - "bond-downdelay 250"
      - "bond-updelay 250"
  - name: bond0.725
    type: manual
    directives:
      - "vlan-raw-device bond0"
  - name: bond0.726
    type: manual
    directives:
      - "vlan-raw-device bond0"
  - name: bond1.728
    type: manual
    directives:
      - "vlan-raw-device bond1"
  - name: br-mgmt
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge-ports bond0.725"
      - "address 172.29.236.{{ member_number }}/22"
      - "dns-nameservers 69.20.0.164 69.20.0.196"
  - name: br-vxlan
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge_ports bond1.728"
      - "address 172.29.240.{{ member_number }}/22"
  - name: br-vlan
    type: manual
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge_ports bond1"
  - name: br-storage
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge_ports bond0.726"
      - "address 172.29.244.{{ member_number }}/22"
  - name: br-snet
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "address 172.29.248.1"
      - "netmask 255.255.252.0"
